export const imageSources = {
  themeWallpaper: require('../images/SPLASH.png'),
  inviteImage: require('../images/Illustration-invite.png'),
  phoneForwarded: require('../images/phone_forwarded.png'),
  eventNote: require('../images/event_note.png'),
  emailImage: require('../images/Email.png'),
  whatsappImage: require('../images/whatsappcircle.png'),
  performanceReport: require('../images/performance_report.png'),
  visibility: require('../images/visibility_off.png'),
  splash: require('../images/SPLASH.png'),
  fingerprint: require('../images/fingerprint.png'),
  logoApp: require('../images/LogoApp.png'),
  pdfFile: require('../images/pdf_file.png'),
  graph1: require('../images/graph1.png'),
  graph2: require('../images/graph2.png'),
  graph3: require('../images/graph3.png'),
  graph4: require('../images/graph4.png'),
  graph5: require('../images/graph5.png'),
  graphColor1: require('../images/graph1-color.png'),
  graphColor2: require('../images/graph2-color.png'),
  graphColor3: require('../images/graph3-color.png'),
  graphColor4: require('../images/graph4-color.png'),
  graphColor5: require('../images/graph5-color.png'),
  sync: require('../images/sync.png'),
  excelFile: require('../images/excel.png'),
};
