import {TaskInterface} from 'components/Task/TaskItem';

export const pendingTaskData = [
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 78,
    priority: 'High',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Low',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 68,
    priority: 'Medium',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 56,
    priority: 'Emergency',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Medium',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 78,
    priority: 'High',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 49,
    priority: 'Low',
    status: 'Resolved',
  },
] as TaskInterface[];
