import {NotificationProps} from './components/NotificationItem';

export const notificationContactList = [
  {
    title: 'Request to share your contact',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'contact',
  },
  {
    title: 'John Doe',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
  },
  {
    title: 'Request to share your contact',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'contact',
  },
  {
    title: 'John Doe',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
  },
  {
    title: 'Request to share your contact',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'contact',
  },
  {
    title: 'John Doe',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
  },
  {
    title: 'Request to share your contact',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'contact',
  },
  {
    title: 'Request to share your contact',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'contact',
  },
  {
    title: 'Request for task re-open',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'Tasks',
    data: {
      name: 'FormData',
      taskName: 'The Walt Disney Company',
      assigneeName: 'Robert Fox',
      date: 'Dec 02, 2021',
      time: '05:00PM',
      taskProgress: 68,
      priority: 'Medium',
      status: 'Reopened',
    },
  },
  {
    title: 'Task has been assigned',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'Tasks',
    data: {
      name: 'FormData',
      taskName: 'The Walt Disney Company',
      assigneeName: 'Robert Fox',
      date: 'Dec 02, 2021',
      time: '05:00PM',
      taskProgress: 68,
      priority: 'Medium',
      status: 'Assigned',
    },
  },
  {
    title: 'Pending Approvals',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'Tasks',
    data: {
      name: 'FormData',
      taskName: 'The Walt Disney Company',
      assigneeName: 'Robert Fox',
      date: 'Dec 02, 2021',
      time: '05:00PM',
      taskProgress: 68,
      priority: 'Medium',
      status: 'Resolved',
    },
  },
  {
    title: 'Pending Approvals',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'Tasks',
    data: {
      name: 'FormData',
      taskName: 'The Walt Disney Company',
      assigneeName: 'Robert Fox',
      date: 'Dec 02, 2021',
      time: '05:00PM',
      taskProgress: 68,
      priority: 'Medium',
      status: 'Re-allocation',
    },
  },
  {
    title: 'Request for task re-allocation',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'Tasks',
    data: {
      name: 'FormData',
      taskName: 'The Walt Disney Company',
      assigneeName: 'Robert Fox',
      date: 'Dec 02, 2021',
      time: '05:00PM',
      taskProgress: 68,
      priority: 'Medium',
      status: 'Re-allocation',
    },
  },
  {
    title: 'John doe commented on #1234 task',
    description: 'Lorem ipsum dolor sit amet, consectetur ',
    date: '30/11/21',
    time: '2:35 PM',
    position: 'Manager',
    type: 'Tasks',
    data: {
      name: 'FormData',
      taskName: 'The Walt Disney Company',
      assigneeName: 'Robert Fox',
      date: 'Dec 02, 2021',
      time: '05:00PM',
      taskProgress: 68,
      priority: 'Medium',
      status: 'Completed',
    },
  },
] as NotificationProps[];
