export enum ReminderStrings {
  asNotification = 'As notification',
  voiceNote = 'VOICENOTE',
  event = 'EVENT',
  task = 'TASK',
  asMail = 'As mail',
  email = 'EMAIL',
  push = 'PUSH',
  custom = 'CUSTOM',
  null = 'NULL',
  voiceNotes = 'voicenotes',
  events = 'events',
  tasks = 'tasks',
  reminder = 'REMINDER',
}
