import {colors} from 'common/theme/colors';
import {AppFonts, FontSizes} from 'common/theme/font';
import {globalScreenWidth} from 'common/utils/ScreenDimensions';
import {Dimensions, Platform, StyleSheet} from 'react-native';
import {respHeight, respWidth} from 'screens/Calendar/utils/responsive';

export const Styles = () => {
  const shareStyles = StyleSheet.create({
    bubble: {
      maxWidth: '50%',
      minWidth: '30%',
    },
    bubbleRight: {
      width: 200,
      alignSelf: 'flex-end',
      alignItems: 'flex-end',
      marginRight: 10,
    },
    input: {
      height: 35,
      borderWidth: 1,
      padding: 10,
      marginTop: 5,
      backgroundColor: colors.white,
      borderColor: colors.white,
      fontFamily: AppFonts.medium,
      fontSize: FontSizes.small,
    },
    header: {
      marginTop: 10,
    },
    headerTop: {
      marginTop: 16,
      marginRight: 10,
    },
    verticalSpace: {
      marginTop: 16,
    },
    groupIcon: {
      height: 40,
      width: 40,
      padding: 7,
      borderRadius: 20,
      backgroundColor: colors.primary_004,
      marginHorizontal: 10,
      marginTop: 5,
    },
    horizontalLine: {
      marginTop: 15,
    },
    name: {
      justifyContent: 'center',
    },
    renderInputToolBar: {
      backgroundColor: colors.white,
      maxHeight: 100,
      marginBottom: 10,
      borderRadius: 3,
      width: globalScreenWidth - 92,
      marginLeft: 20,
    },
    mic: {
      marginLeft: 10,
      marginBottom: 10,
      height: 32,
      width: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    view: {
      width: 16,
      height: '100%',
      backgroundColor: colors.grey_001,
      borderTopColor: colors.grey_001,
    },
    smallView: {
      width: 5,
      height: '100%',
      backgroundColor: colors.grey_001,
    },
    TextInput: {
      width: Dimensions.get('screen').width / 2,
      marginLeft: 10,
      marginBottom: Platform.OS === 'ios' ? respWidth(15) : undefined,
    },
    sendIcon: {
      backgroundColor: colors.primary,
      paddingLeft: 13,
      padding: 10,
      borderRadius: 2,
    },
    iconsBottom: {
      marginBottom: 12,
      marginRight: 10,
    },
    attachFile: {
      marginBottom: 10,
    },
    nameTime: {
      color: colors.black,
    },
    leftNameTime: {
      color: colors.black,
      marginRight: 10,
    },
    textViewLeft: {
      marginTop: 10,
      backgroundColor: colors.white,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
      // maxWidth: Dimensions.get('screen').width / 2,
      minWidth: Dimensions.get('screen').width / 4.5,
    },
    textViewRight: {
      marginBottom: 10,
      backgroundColor: colors.grey_008,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 6,
      minWidth: Dimensions.get('screen').width / 4.5,
    },
    text: {
      paddingHorizontal: 8,
      paddingTop: 5,
      paddingBottom: 12,
      marginBottom: 3,
    },
    seeMoreText: {color: colors.blue_001},
    noAttachmentTextStyle: {
      // width: Dimensions.get('screen').width / 2.5,
      paddingHorizontal: 10,
      paddingTop: 5,
      paddingBottom: 12,
      marginBottom: 3,
      maxWidth: Dimensions.get('screen').width / 1.4,
    },
    tickIcon: {
      marginLeft: 3,
      marginRight: 3,
    },
    headName: {
      marginLeft: 10,
    },
    timeTickView: {
      alignSelf: 'flex-end',
    },
    groupName: {marginLeft: 10, marginTop: 3},
    timeTick: {position: 'absolute', right: 0, bottom: 3, top: 5},
    renderDay: {
      color: colors.black,
      textAlign: 'center',
      marginTop: 16,
    },
    receiverImage: {
      height: 158,
      width: 152,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
      borderWidth: 3,
      borderColor: colors.white,
    },
    senderImage: {
      height: 158,
      width: 152,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 6,
      borderWidth: 3,
      borderColor: colors.grey_008,
      paddingBottom: 50,
    },
    receiverFileSize: {color: colors.black},
    docxView: {
      height: 57,
      width: '110%',
      right: 20,
      backgroundColor: colors.grey_008,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 6,
    },
    docxFileName: {
      height: 35,
      width: '90%',
      backgroundColor: colors.grey_013,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 10,
      marginBottom: 3,
      marginTop: 5,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 6,
    },
    dot: {
      height: 3,
      width: 3,
      borderRadius: 3,
      backgroundColor: colors.black,
    },
    docxFooter: {marginLeft: 10},
    selectedReceiverMessageView: {
      backgroundColor: colors.grey_013,
      width: Dimensions.get('screen').width,
      paddingBottom: 10,
    },
    selectedSenderMessageView: {
      backgroundColor: colors.grey_013,
      width: Dimensions.get('screen').width,
      paddingBottom: 10,
    },
    receiverMessageSelectedView: {
      marginLeft: 16,
      marginTop: 6,
      marginBottom: 10,
      width: Dimensions.get('screen').width / 1.4,
    },
    senderMessageView: {
      marginTop: 16,
      width: Dimensions.get('screen').width / 1.4,
      right: 0,
      justifyContent: 'flex-end',
      alignSelf: 'flex-end',
    },
    marginReceiverMessage: {
      marginBottom: -8,
    },
    mentionBox: {
      height: 200,
      width: respWidth(322),
      backgroundColor: colors.white,
      marginBottom: respHeight(20),
      marginLeft: -45,
    },
    suggestionBox: {height: 200, paddingLeft: 20},
    pressableOption: {padding: 12},
    suggestionDivider: {marginRight: 25, marginVertical: 5},
    sendButton: {
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      height: 42,
      width: 42,
      borderRadius: 3,
      marginLeft: 8,
      marginBottom: 15,
    },
    data: {
      backgroundColor: colors.white,
      height: 100,
      width: 100,
      marginBottom: 10,
      marginLeft: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    centeredView: {
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      borderRadius: 3,
      marginTop: 5,
    },
    receiverCenteredView: {
      justifyContent: 'flex-end',
      alignItems: 'flex-start',
      borderRadius: 3,
      marginTop: 5,
    },
    modalView: {
      backgroundColor: 'white',
      width: 234,
      height: 117,
      justifyContent: 'center',
    },
    shareVia: {
      padding: 15,
    },
    imageMargin: {marginLeft: 53},
    textMargin: {
      maxWidth: Dimensions.get('screen').width / 2,
      minWidth: Dimensions.get('screen').width / 3,
      left: 20,
    },
    personaMargin: {marginLeft: 23},
    wordFileName: {width: 170},
    isSelectedSenderMessage: {
      backgroundColor: colors.grey_013,
      width: Dimensions.get('screen').width,
      paddingBottom: 10,
      alignItems: 'flex-end',
    },
    imageSendTime: {alignSelf: 'flex-end'},
    receiverPersona: {marginTop: 10},
    senderPersona: {marginBottom: 8},
    audioView: {
      height: 72,
      width: Dimensions.get('screen').width / 1.4,
      // right: 80,
      backgroundColor: colors.grey_008,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomLeftRadius: 6,
    },
    fileIcon: {
      alignSelf: 'center',
      justifyContent: 'center',
    },
    fileIconAudio: {
      marginLeft: 10,
    },
    waveForm: {
      height: 20,
      width: Dimensions.get('screen').width / 2.5,
      marginTop: 10,
    },
    micAudio: {position: 'absolute', right: -4, bottom: 0},
    viewAudio: {
      marginLeft: 10,
      marginTop: 5,
      width: Dimensions.get('screen').width - 94,
    },
    waveView: {marginTop: 10, marginLeft: 8},
    audioFooter: {marginRight: 70, top: 6},
    audioTime: {right: -12},
    pausePlayIcon: {marginTop: 10, marginRight: 10},
    pdfIcon: {marginLeft: 10},
    containerStyle: {
      flex: 1,
    },
    flatlistStyle: {
      flexGrow: 1,
    },
    mentionInput: {
      fontFamily: AppFonts.regular,
      fontSize: FontSizes.regular,
      color: '#000',
    },
    BoxStyle: {
      backgroundColor: colors.white,
      borderRadius: 3,
      height: 70,
      flex: 1,
      paddingHorizontal: 4,
    },

    CloseIconStyle: {
      paddingHorizontal: 16,
    },
    timeStyleAudio: {
      paddingLeft: Dimensions.get('screen').width / 3.5,
      color: colors.black,
      // marginBottom: 10,
      position: 'absolute',
      bottom: 2,
    },
    fileUploadingBottom: {
      height: 50,
    },
    attachIconStyle: {
      top: 15,
    },
    filterWidth: {
      height: 77,
      width: 166,
      // backgroundColor: colors.white,
      borderTopLeftRadius: 6,
      borderBottomLeftRadius: 6,
      borderBottomRightRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: Dimensions.get('screen').width / 3,
      marginTop: 22,
    },
    receiverName: {
      fontSize: FontSizes.xSmall,
      width: respWidth(150),
      position: 'absolute',
      top: -10,
    },
    deletedMsgView: {
      padding: 10,
      marginBottom: 10,
      marginRight: 10,
    },
    deletedMsgTxt: {
      fontStyle: 'italic',
    },
    excelIcon: {height: 20, width: 20, marginRight: 12},
  });
  return shareStyles;
};
