import {ReportProps} from 'components/Report/ReportItem';

export const ownerReportList = [
  {
    name: 'Jenny Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Wade Warren',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Marvin McKinney',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Esther Howard',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Kristin Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jane Cooper',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Leslie Alexander',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
] as ReportProps[];

export const managerReportList = [
  {
    name: 'Marvin McKinney',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Esther Howard',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jenny Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Wade Warren',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Kristin Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jane Cooper',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Leslie Alexander',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
] as ReportProps[];

export const employeeReportList = [
  {
    name: 'Kristin Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jane Cooper',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Marvin McKinney',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Esther Howard',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jenny Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Wade Warren',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Leslie Alexander',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
];

export const vendorReportList = [
  {
    name: 'Leslie Alexander',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Esther Howard',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jenny Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Wade Warren',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Marvin McKinney',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Esther Howard',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Kristin Watson',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
  {
    name: 'Jane Cooper',
    company: 'The Walt Disney Company',
    assigned: '10',
    inprogress: '6',
    overdue: '1',
  },
] as ReportProps[];
