import {TaskInterface} from 'components/Task/TaskItem';

export const linkedTaskData = [
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 78,
    priority: 'High',
    status: 'In-progress',
    self: true,
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Low',
    status: 'Completed',
    self: true,
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 68,
    priority: 'Medium',
    status: 'Reopened',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 56,
    priority: 'Emergency',
    status: 'Resolved',
    self: true,
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Medium',
    status: 'Assigned',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 78,
    priority: 'High',
    status: 'Resolved',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 49,
    priority: 'Low',
    status: 'In-progress',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Medium',
    status: 'Assigned',
    self: true,
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Low',
    status: 'Completed',
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 63,
    priority: 'Low',
    status: 'Overdue',
  },
] as TaskInterface[];

export const selfAssignedTaskData = [
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 78,
    priority: 'High',
    status: 'In-progress',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Low',
    status: 'Completed',
    self: true,
  },
  {
    name: 'Subtask',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 68,
    priority: 'Medium',
    status: 'Reopened',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 56,
    priority: 'Emergency',
    status: 'Resolved',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Medium',
    status: 'Assigned',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 78,
    priority: 'High',
    status: 'Resolved',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 49,
    priority: 'Low',
    status: 'In-progress',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Medium',
    status: 'Assigned',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 100,
    priority: 'Low',
    status: 'Completed',
    self: true,
  },
  {
    name: 'FormData',
    taskName: 'The Walt Disney Company',
    assigneeName: 'Robert Fox',
    date: 'Dec 02, 2021',
    time: '05:00PM',
    taskProgress: 63,
    priority: 'Low',
    status: 'Overdue',
    self: true,
  },
] as TaskInterface[];
